name: Assemble Luna image

on:
  push:
    branches:
      - main
    paths:
      - '.image_parts/ready'

permissions:
  contents: write

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Assemble image
        shell: bash
        run: |
          cat .image_parts/part_* | base64 --decode > Luna_Pirate.webp
          rm -rf .image_parts
          rm .github/workflows/assemble-luna-image.yml
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Add Luna Pirate image [skip ci]"
          git push
